# Generated by Django 5.2.8 on 2025-12-10 19:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique conversation identifier', primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, default='New chat', help_text='Conversation title, typically first user message', max_length=255)),
                ('model_id', models.CharField(db_index=True, help_text='LLM model identifier (fin, bedrock-claude, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Conversation creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Last message timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp (NULL if active)', null=True)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at', 'deleted_at'], name='conv_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique message identifier', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], db_index=True, help_text='Message role: user, assistant, or system', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('protegrity_data', models.JSONField(blank=True, help_text='Protegrity processing metadata (PII detections, redactions, etc.)', null=True)),
                ('pending', models.BooleanField(db_index=True, default=False, help_text='True if awaiting LLM response (for async models)')),
                ('blocked', models.BooleanField(db_index=True, default=False, help_text='True if message was blocked by guardrails')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Message creation timestamp')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('conversation', models.ForeignKey(help_text='Parent conversation', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='msg_conv_time_idx')],
            },
        ),
    ]
