# Generated by Django 5.2.8 on 2025-12-10 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.CharField(help_text="Unique identifier (e.g., 'fin', 'bedrock-claude')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Fin AI', 'Claude 3.5 Sonnet')", max_length=100)),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('bedrock', 'Amazon Bedrock'), ('intercom', 'Intercom Fin'), ('azure', 'Azure OpenAI'), ('google', 'Google AI'), ('custom', 'Custom')], help_text='Provider category', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Model description and capabilities')),
                ('model_identifier', models.CharField(blank=True, help_text="Provider-specific model ID (e.g., 'anthropic.claude-3-5-sonnet-v2')", max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable/disable model for selection')),
                ('requires_polling', models.BooleanField(default=False, help_text='True for async models (Fin AI), False for sync (Bedrock)')),
                ('max_tokens', models.IntegerField(default=4096, help_text='Maximum context window size')),
                ('supports_streaming', models.BooleanField(default=False, help_text='Supports streaming responses')),
                ('cost_per_1k_input_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='Pricing: USD per 1K input tokens', max_digits=10, null=True)),
                ('cost_per_1k_output_tokens', models.DecimalField(blank=True, decimal_places=6, help_text='Pricing: USD per 1K output tokens', max_digits=10, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Model-specific config (API keys, endpoints, parameters)')),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in UI (lower = higher priority)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'db_table': 'llm_providers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(help_text="Unique identifier (e.g., 'data-protection-expert')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name (e.g., 'Data Protection Expert')", max_length=100)),
                ('description', models.TextField(help_text='Agent purpose and capabilities')),
                ('system_prompt', models.TextField(help_text='Base system instructions for the agent')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable/disable agent')),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for UI', max_length=50)),
                ('color', models.CharField(default='#FA5A25', help_text='Hex color for UI theme', max_length=7)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in UI')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Agent-specific settings (temperature, max_tokens, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_llms', models.ManyToManyField(blank=True, help_text='LLMs this agent can use', related_name='agents', to='core.llmprovider')),
                ('default_llm', models.ForeignKey(help_text='Default LLM for this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_agents', to='core.llmprovider')),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.CharField(help_text="Unique identifier (e.g., 'protegrity-redact')", max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('tool_type', models.CharField(choices=[('protegrity', 'Protegrity Data Protection'), ('api', 'External API'), ('function', 'Function Call'), ('database', 'Database Query'), ('search', 'Search/Retrieval'), ('custom', 'Custom Tool')], help_text='Tool category', max_length=20)),
                ('description', models.TextField(help_text='What this tool does')),
                ('function_schema', models.JSONField(default=dict, help_text='OpenAI function calling schema / tool definition')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable/disable tool')),
                ('requires_auth', models.BooleanField(default=True, help_text='Requires API key or authentication')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Tool-specific config (API endpoints, credentials, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, help_text='Agents that can use this tool', related_name='tools', to='core.agent')),
            ],
            options={
                'db_table': 'tools',
                'ordering': ['name'],
            },
        ),
    ]
