# Generated by Django 5.2.8 on 2025-12-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_llmprovider_agent_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='primary_agent',
            field=models.ForeignKey(blank=True, help_text='Default agent for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.agent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='primary_llm',
            field=models.ForeignKey(blank=True, help_text='Default LLM provider for this conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='core.llmprovider'),
        ),
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent that generated this message (assistant messages)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.agent'),
        ),
        migrations.AddField(
            model_name='message',
            name='llm_provider',
            field=models.ForeignKey(blank=True, help_text='LLM provider/model used for this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.llmprovider'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['llm_provider', 'created_at'], name='msg_llm_time_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['agent', 'created_at'], name='msg_agent_time_idx'),
        ),
    ]
