# Generated by Django 5.2.8 on 2025-12-11 21:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_primary_agent_conversation_primary_llm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='min_role',
            field=models.CharField(choices=[('PROTEGRITY', 'Protegrity Employee / Admin'), ('STANDARD', 'Standard User')], db_index=True, default='PROTEGRITY', help_text='Minimum user role required to see/use this agent', max_length=32),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='min_role',
            field=models.CharField(choices=[('PROTEGRITY', 'Protegrity Employee / Admin'), ('STANDARD', 'Standard User')], db_index=True, default='PROTEGRITY', help_text='Minimum user role required to see/use this model', max_length=32),
        ),
        migrations.AddField(
            model_name='tool',
            name='min_role',
            field=models.CharField(choices=[('PROTEGRITY', 'Protegrity Employee / Admin'), ('STANDARD', 'Standard User')], db_index=True, default='PROTEGRITY', help_text='Minimum user role required to see/use this tool', max_length=32),
        ),
        migrations.AlterField(
            model_name='message',
            name='protegrity_data',
            field=models.JSONField(blank=True, help_text='Protegrity processing metadata (PII detections, redactions, etc.)\n        \n        Schema for user messages (input protection):\n        {\n            "original_text": "raw user input",\n            "processed_text": "text sent to LLM (redacted/protected)",\n            "should_block": bool,\n            "guardrails": {"outcome": "accepted"|"rejected", "risk_score": float, ...},\n            "discovery": {"EMAIL": [{"entity_text": "...", "score": 0.99, ...}], ...},\n            "redaction": {"success": bool, "method": "redact"},\n            "mode": "redact"|"protect"\n        }\n        \n        Schema for assistant messages (output protection):\n        {\n            "original_response": "raw LLM output",\n            "processed_response": "text shown to user (redacted if needed)",\n            "should_filter": bool,\n            "guardrails": {"outcome": "accepted"|"rejected", "risk_score": float, ...},\n            "discovery": {"EMAIL": [{...}], ...},\n            "redaction": {"success": bool, "method": "redact"}\n        }\n        \n        May also contain {"tool_results": [...]} for tool execution tracking.\n        ', null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROTEGRITY', 'Protegrity Employee / Admin'), ('STANDARD', 'Standard User')], db_index=True, default='STANDARD', help_text='Role governs access to LLMs, Agents, and Tools', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated Django user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique key identifier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable label for this key (e.g., 'Production Server')", max_length=100)),
                ('prefix', models.CharField(db_index=True, help_text='First 8 chars of key for fast lookup', max_length=16)),
                ('hashed_key', models.CharField(help_text='Hashed full key (never store plaintext)', max_length=128)),
                ('scopes', models.JSONField(blank=True, default=list, help_text="List of scopes, e.g. ['chat', 'models'] - for future use")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Revoke key by setting to False')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Key creation timestamp')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last successful authentication with this key', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date', null=True)),
                ('user', models.ForeignKey(help_text='Key owner - inherits their role and permissions', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prefix', 'is_active'], name='apikey_lookup_idx')],
            },
        ),
    ]
